SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS enum_configs (
  id         BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  field      VARCHAR(64) NOT NULL UNIQUE COMMENT 'e.g. app_id, platform_id, user_mode',
  labels     JSON NOT NULL            COMMENT '{"1":"AppA","2":"AppB"}',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;